# Generated by Django 3.1 on 2020-08-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(max_length=280)),
                ('post_or_roast', models.BooleanField()),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('submission_time', models.DateTimeField()),
            ],
        ),
    ]
