# Generated by Django 3.1 on 2020-08-21 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GhostPostApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='posts',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
